# -*- coding: utf-8 -*-
"""Automation_upload.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ypapHLD_2NG_Ix8PIVMg6XJOzhOUcRDa
"""

#Sample data 
import pandas as pd

dfdict= {'Ticker': ['AMD', "LRCX" , "INCY"],
    'Higher V Open': [11.708999, 11.109498	,10.074349],	
    'Higher V Close': [11.700221,10.661992 , 8.736313]}

df = pd.DataFrame(dfdict)

df

#upload automation

!pip install pygsheets
import pygsheets
gc = pygsheets.authorize(service_file='/content/encoded-antler-352915-34b57b687aa7.json') #this requires your json key in your remote computer 
j = gc.open_by_url('https://docs.google.com/spreadsheets/d/10ZwDAlofYxwb6uwrjDi5orhe7rHq3efQUdzSo3dOMGQ/edit#gid=0')
wks = j.sheet1 
wks.set_dataframe(df,(1,1))